if: tag IS present

language: bash
services: docker

before_script:
- docker build -t amixlabs/pdf-service:latest -t amixlabs/pdf-service:$TRAVIS_TAG -t amixlabs/pdf-service:${TRAVIS_TAG//.*} .

script:
- docker run --rm -it amixlabs/pdf-service node --version
- docker run --rm -it amixlabs/pdf-service yarn --version
- docker run --rm -it amixlabs/pdf-service bash -c '[[ -f src/server.js ]]'

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push amixlabs/pdf-service
